### ISSUE TITLE
Typo in octoprint_psucontrol_settings.js ?

### ISSUE THREAD

**Issue by kenrf** [VRGhost/OctoPrint-PSUControl-Meross#12]
I believe theres a typo in octoprint_psucontrol_settings.js, line 119:
 if (!username || !password || !device_id) {
should actually be 
 if (!username || !password || !device_ids) {

Have been having issues testing the toggle feature in the plugin settings page (it just doesn't work) and I think this is my issue. Not setup to debug or dev octoprint plugins so figured i'd create an issue to be checked.

**Comment by IljaOrlovs** [comment]
Oh, right.

Yes, I've just added multiple device IDs support the other week, forgot to check the JS. Thank you.

**Comment by IljaOrlovs** [comment]
Fixed in 0.13.1.

Thank you for reporting this.
