### ISSUE TITLE
login failed. async from user, missing 1 positional argument: api base url

### ISSUE THREAD

**Issue by motorm182** [VRGhost/OctoPrint-PSUControl-Meross#16]
My pi went down during a storm corrupting the card so when i reloaded a new octopi image, I can no longer log in. error message. async_from_user_password() missing 1 required positional argument: 'api_base_url' appears above login. Hopefully its an easy fix. In the bin I can see the code but not sure what is missing or incorrect in it. Any help is appreciated as the meross plugs have been working great for my home automation and the printer

**Comment by DaveLinger** [comment]
I have the same problem and error.

**Comment by jeloneal** [comment]
Please update to latest version 0.13.3. The necessary changes to make it work with latest Meross API are implemented there.
