### ISSUE TITLE
Unable to connect to Meross service - 404

### ISSUE THREAD

**Issue by jeloneal** [VRGhost/OctoPrint-PSUControl-Meross#17]
All of a sudden, the plugin cannot connect to the Meross services anymore:

![image](https://github.com/VRGhost/OctoPrint-PSUControl-Meross/assets/48490942/288c828b-246c-454a-b419-0b83a6c04d1b)

Could it be that they changed something on their side?

**Comment by jeloneal** [comment]
Update: found out that they have added another connection parameter, location (eu/us/...). Can you please update the project to make it work with that change again? Thanks a lot in advance!

**Comment by jeloneal** [comment]
Found a pull request created by luizbon. Gave it a try, found a problem, fixed it and created an updated pull request. Please check and consider merging it. Solved the problem for me.

Thanks for the great plugin @VRGhost

**Comment by IljaOrlovs** [comment]
Hello,

Thank you for sending the last message - I did notice the email.

I've merged the PR, but the package build has failed.  Would you kindly take a look?  I'm bit too distracted to.
[5_Build packages.txt](https://github.com/VRGhost/OctoPrint-PSUControl-Meross/files/13929373/5_Build.packages.txt)

**Comment by IljaOrlovs** [comment]
I've added you as a collaborator, as I do not have Meross wifi switches anymore (I've migrated to Zigbee/Hubitat), so I have no way of checking if the thing actually works.

**Comment by IljaOrlovs** [comment]
Please do tell if the collaborator thing works or not - I have never done that for public repos, so I do not know if you can push, see CI logs and such.

**Comment by IljaOrlovs** [comment]
So, to make public release you just make a git version tag, and CI should do the rest.

**Comment by jeloneal** [comment]
Got the invite, thank you. Will check how to fix that build issue. Seems related to luizbon's PR. Will trigger the release once fixed.

**Comment by jeloneal** [comment]
Fixed with 0.13.3
