### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by noone-g** [VRGhost/OctoPrint-PSUControl-Meross#7]
Can't turn on with the following error message.

'MerossHttpClient' object has no attribute 'logout'

**Comment by xlordxcheater** [comment]
'MerossHttpClient' object has no attribute 'logout'

Same error here

**Comment by IljaOrlovs** [comment]
Hello!
Apologies for not responding for a _bit_. 

I've just released the `0.12.1` version with the fix.
