### ISSUE TITLE
Enable scenes in addition to devices or switching multiple devices 

### ISSUE THREAD

**Issue by jeloneal** [VRGhost/OctoPrint-PSUControl-Meross#9]
The Meross app allows creation of scenes like triggering several outlets together etc. I would like to use that to switch printer and a lamp in a second outlet together. Maybe you could add scenes or allow switching of multiple devices with the plugin? Would be great!

thanks in advance for considering

**Comment by IljaOrlovs** [comment]
Hello,

So I was not able to find _scene_ handling in the underlying `meross-iot` library I'm using to communicate with Meross servers.

However, I have just released 0.13.0 that allows you to pick multiple devices to be controlled with the PSU switch (you need to hold Ctrl/Cmd while picking the options).

Cheers/

**Comment by jeloneal** [comment]
Thanks. Will check that out. Sounds like it will solve my problem.

**Comment by jeloneal** [comment]
Quick feedback: works perfectly and solves my initial issue 👍 Thanks a lot!

**Comment by IljaOrlovs** [comment]
Thank you!

And definitely thank you for the patience - I sure have taken a bit of time to come around.
